"""notifications and procurement domains

Revision ID: 0e5c6198ae2a
Revises: f30b14c24906
Create Date: 2026-09-28 10:32:01.123037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5c6198ae2a'
down_revision: Union[str, None] = 'f30b14c24906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('whatsapp', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_notif_pref_user_category')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1024), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_read', ['recipient_user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_product_id'), ['product_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('items_total', sa.Float(), nullable=False),
    sa.Column('freight', sa.Float(), nullable=False),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('reorder_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('weekly_velocity', sa.Float(), nullable=False),
    sa.Column('weeks_of_cover', sa.Float(), nullable=True),
    sa.Column('stock_at_time', sa.Integer(), nullable=False),
    sa.Column('suggested_qty', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'product_id', name='uq_suggestion_run_product')
    )
    with op.batch_alter_table('reorder_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reorder_suggestions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reorder_suggestions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reorder_suggestions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reorder_suggestions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reorder_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reorder_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_reorder_suggestions_run_id'))
        batch_op.drop_index(batch_op.f('ix_reorder_suggestions_product_id'))
        batch_op.drop_index(batch_op.f('ix_reorder_suggestions_org_id'))

    op.drop_table('reorder_suggestions')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_org_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_po_id'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index('ix_notifications_recipient_read')
        batch_op.drop_index(batch_op.f('ix_notifications_org_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
