"""warehouse domain 22 (warehouses, stock items, movements, pick waves), users.phone, notification outbox 39

Revision ID: eb9661601ad6
Revises: 0e5c6198ae2a
Create Date: 2026-09-28 14:02:22.657978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9661601ad6'
down_revision: Union[str, None] = '0e5c6198ae2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=4096), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_outbox_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_outbox_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_outbox_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_outbox_user_id'), ['user_id'], unique=False)

    op.create_table('pick_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('picked_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pick_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pick_lines_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pick_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pick_lines_wave_id'), ['wave_id'], unique=False)

    op.create_table('pick_waves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_number', sa.String(length=30), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wave_number')
    )
    with op.batch_alter_table('pick_waves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pick_waves_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pick_waves_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pick_waves_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_stock_item_wh_product')
    )
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_items_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index('ix_stock_movements_product_created', ['product_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('address', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_status'))
        batch_op.drop_index(batch_op.f('ix_warehouses_org_id'))

    op.drop_table('warehouses')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index('ix_stock_movements_product_created')
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_items_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_items_product_id'))

    op.drop_table('stock_items')
    with op.batch_alter_table('pick_waves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pick_waves_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_pick_waves_status'))
        batch_op.drop_index(batch_op.f('ix_pick_waves_org_id'))

    op.drop_table('pick_waves')
    with op.batch_alter_table('pick_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pick_lines_wave_id'))
        batch_op.drop_index(batch_op.f('ix_pick_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_pick_lines_order_id'))

    op.drop_table('pick_lines')
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_outbox_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_notification_outbox_org_id'))
        batch_op.drop_index(batch_op.f('ix_notification_outbox_channel'))

    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
